#!/usr/bin/env sh
# . "$(dirname "$0")

# Check if the commit includes changes in the frontend or backend
STAGED_FILES=$(git diff --name-only --cached)

if echo "$STAGED_FILES" | grep -q "packages/frontend"; then
  echo "Changes detected in frontend. Running lerna-build..."
  npm run lerna-build
elif echo "$STAGED_FILES" | grep -q "packages/backend"; then
  echo "Changes detected in backend. Skipping lerna-build for backend-only changes."
else
  echo "No changes detected in frontend or backend. Skipping lerna-build."
fi