#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

# Automatically format files first
npm run prettier:format

# Stage the formatted files
git add .

# Check for any remaining formatting issues
npm run prettier:check

# Build the project
npm run lerna-build