#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

# Automatically format files first
npm run prettier:format

# Stage only the files that were modified by Prettier
git diff --name-only --cached --diff-filter=ACM | grep -E "^(packages/frontend|packages/backend)" | xargs git add

# Check for any remaining formatting issues
npm run prettier:check

# Check if the commit includes changes in the frontend or backend
STAGED_FILES=$(git diff --name-only --cached)

if echo "$STAGED_FILES" | grep -q "packages/frontend"; then
  echo "Changes detected in frontend. Running lerna-build..."
  npm run lerna-build
elif echo "$STAGED_FILES" | grep -q "packages/backend"; then
  echo "Changes detected in backend. Skipping lerna-build for backend-only changes."
else
  echo "No changes detected in frontend or backend. Skipping lerna-build."
fi